import { green, lightBlue, deepPurple } from "@mui/material/colors";

export const subjectList: Subject[] = [
  {
    id: 1,
    name: "Toán học",
    color: "#2563EB",
    icon: "solar:calculator-outline",
    category: "Tự nhiên",
    tabs: ["a00", "a01"],
    weight: 2,
  },
  {
    id: 2,
    name: "Vật lý",
    color: "#1D4ED8",
    icon: "solar:bolt-outline",
    category: "Tự nhiên",
    tabs: ["a00", "a01", "a02", "b00"],
    weight: 1,
  },
  {
    id: 3,
    name: "Hóa học",
    color: "#0EA5E9",
    icon: "solar:test-tube-outline",
    category: "Tự nhiên",
    tabs: ["a00", "a01", "a02", "b00"],
    weight: 1,
  },
  {
    id: 4,
    name: "Sinh học",
    color: "#0284C7",
    icon: "solar:dna-outline",
    category: "Tự nhiên",
    tabs: ["b00", "b08"],
    weight: 1,
  },
  {
    id: 5,
    name: "Ngữ văn",
    color: "#8B5CF6",
    icon: "solar:book-2-outline",
    category: "Xã hội",
    tabs: ["c00", "d01"],
    weight: 2,
  },
  {
    id: 6,
    name: "Lịch sử",
    color: "#7C3AED",
    icon: "solar:history-outline",
    category: "Xã hội",
    tabs: ["c00"],
    weight: 1,
  },
  {
    id: 7,
    name: "Địa lý",
    color: "#A855F7",
    icon: "solar:map-outline",
    category: "Xã hội",
    tabs: ["c00"],
    weight: 1,
  },
  {
    id: 8,
    name: "Tiếng Anh",
    color: "#9333EA",
    icon: "solar:chat-line-outline",
    category: "Xã hội",
    tabs: ["d01"],
    weight: 2,
  },
  {
    id: 9,
    name: "Tin học",
    color: "#F97316",
    icon: "solar:laptop-outline",
    category: "Tự chọn",
    tabs: ["a01", "d01"],
    weight: 1,
  },
  {
    id: 10,
    name: "Công nghệ",
    color: "#EA580C",
    icon: "solar:code-square-outline",
    category: "Tự chọn",
    tabs: ["a01", "d01"],
    weight: 1,
  },
  {
    id: 11,
    name: "Giáo dục công dân",
    color: "#EF4444",
    icon: "solar:shield-check-bold",
    category: "Tự chọn",
    tabs: ["c14", "d01"],
    weight: 1,
  },
  {
    id: 12,
    name: "Giáo dục thể chất",
    color: "#DC2626",
    icon: "solar:dumbbell-outline",
    category: "Tự chọn",
    tabs: ["t00", "t01"],
    weight: 1,
  },
  {
    id: 13,
    name: "Giáo dục quốc phòng – an ninh",
    color: "#F43F5E",
    icon: "solar:shield-check-outline",
    category: "Tự chọn",
    tabs: ["n00"],
    weight: 1,
  },
  {
    id: 14,
    name: "Hoạt động trải nghiệm – hướng nghiệp",
    color: "#E11D48",
    icon: "solar:rocket-outline",
    category: "Tự chọn",
    tabs: ["m00"],
    weight: 1,
  },
  {
    id: 15,
    name: "Nội dung giáo dục của địa phương",
    color: "#EC4899",
    icon: "solar:hand-heart-outline",
    category: "Tự chọn",
    tabs: ["m00"],
    weight: 1,
  },
  {
    id: 16,
    name: "Tiếng dân tộc thiểu số",
    color: "#DB2777",
    icon: "solar:chat-line-outline",
    category: "Tự chọn",
    tabs: ["m00"],
    weight: 1,
  },
];

export const exams: Exam[] = [
  {
    id: 1,
    name: "Miệng",
    weight: 1,
    icon: "solar:chat-line-outline",
    color: lightBlue[600],
  },
  {
    id: 2,
    name: "15 phút",
    weight: 1,
    icon: "solar:history-outline",
    color: lightBlue[700],
  },
  {
    id: 3,
    name: "1 tiết",
    weight: 2,
    icon: "solar:clock-circle-outline",
    color: green[500],
  },
  {
    id: 4,
    name: "Kỳ",
    weight: 3,
    icon: "solar:notes-bold-duotone",
    color: deepPurple[500],
  },
];
